name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  check_format:
    runs-on: ubuntu-latest
    name: Check format
    strategy:
      matrix:
        elixir: ['1.13.2']
        otp: ['24.x']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ matrix.otp }}-${{ matrix.elixir }}-mix-
      - name: Set up Elixir
        uses: erlef/setup-elixir@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v2
        id: mix-cache # id to use in retrieve action
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install mix dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true' # only if something in mix.lock changed compared to the cached one
        run: mix deps.get
      - name: Check format
        run: mix format --check-formatted

  tests:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['21.x', '22.x', '23.x', '24.x']
        elixir: ['1.10.x', '1.11.x', '1.12.x', '1.13.x']
        exclude:
          - otp: '21.x'
            elixir: '1.12.x'
          - otp: '21.x'
            elixir: '1.13.x'
          - otp: '24.x'
            elixir: '1.10.x'
          - otp: '23.x'
            elixir: '1.10.x'
          - otp: '24.x'
            elixir: '1.11.x'
    needs: check_format
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v2
        id: mix-cache # id to use in retrieve action
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install mix dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true' # only if something in mix.lock changed compared to the cached one
        run: mix deps.get
      - name: Run Tests
        run: mix test

  interop-tests:
    strategy:
      matrix:
        otp: ['21.x', '22.x', '23.x', '24.x']
        elixir: ['1.10.x', '1.11.x', '1.12.x', '1.13.x']
        exclude:
          - otp: '21.x'
            elixir: '1.12.x'
          - otp: '21.x'
            elixir: '1.13.x'
          - otp: '24.x'
            elixir: '1.10.x'
          - otp: '23.x'
            elixir: '1.10.x'
           - otp: '24.x'
            elixir: '1.11.x'
    runs-on: ubuntu-latest
    name: Interop tests
    needs: check_format
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: interop-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            interop-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v2
        id: mix-cache # id to use in retrieve action
        with:
          path: deps
          key: ${{ runner.os }}-interop-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install mix dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true' # only if something in mix.lock changed compared to the cached one
        run: mix deps.get
        working-directory: ./interop
      - name: Run interop tests
        run: mix run script/run.exs
        working-directory: ./interop

  check_release:
    runs-on: ubuntu-latest
    name: Check release
    needs: check_format
    strategy:
      matrix:
        otp: [ '21.x', '22.x','23.x','24.x']
        elixir: [ '1.10.x','1.11.x','1.12.x','1.13.x']
        exclude:
          - otp: '21.x'
            elixir: '1.12.x'
          - otp: '21.x'
            elixir: '1.13.x'
          - otp: '24.x'
            elixir: '1.10.x'
           - otp: '23.x'
            elixir: '1.10.x'
          - otp: '24.x'
            elixir: '1.11.x'
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v2
        id: mix-cache # id to use in retrieve action
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install mix dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true' # only if something in mix.lock changed compared to the cached one
        run: mix deps.get
      - name: Build hex
        run: mix hex.build
      - name: Generate docs
        run: mix docs
